import './ContentPage.css'
import { Footer, Header, StoreButtons } from './SiteChrome'

function Guide() {
  return (
    <><Header /><main id="main-content" className="content-page">
      <header className="content-hero"><div className="container content-hero-inner"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>Di2 button setup guide</span></nav><p className="eyebrow">Step-by-step guide</p><h1>How to control your phone with Shimano Di2 buttons</h1><p className="content-hero-intro">Pair a Bluetooth-enabled Di2 bike, map its hood buttons, and control music, volume, lights, a virtual bell, and more from your handlebars.</p></div></header>
      <div className="container content-layout"><article className="content-main">
        <div className="answer-box"><strong>Can Di2 buttons control a phone?</strong><p>Yes. Bike Connect reads programmable Shimano Di2 hood or top-button presses over Bluetooth and maps them to supported actions on iPhone, iPad, Android, Mac, or Apple Watch.</p></div>
        <section id="requirements"><h2>What you need</h2><div className="requirements-grid"><div className="requirement-card"><strong>Compatible Di2 bike</strong><p>Bluetooth LE groupset with readable hood, top, or shift-switch buttons</p></div><div className="requirement-card"><strong>Bike Connect</strong><p>Installed from the App Store or Google Play</p></div><div className="requirement-card"><strong>Bluetooth access</strong><p>Permission granted on the device you want to control</p></div><div className="requirement-card"><strong>No competing connection</strong><p>Other bike apps disconnected before pairing</p></div></div><p>Current DURA-ACE R9200, ULTEGRA R8100, SHIMANO 105 R7100, GRX RX825/RX827, and wireless MTB Di2 systems include Bluetooth LE. Many 11-speed road, GRX, XTR, and DEORE XT systems require an EW-WU101, EW-WU111, or SC-MT800 wireless unit.</p></section>
        <section id="pair"><h2>Pair your Di2 bike</h2><ol className="numbered-steps"><li><strong>Wake the bike.</strong> Shift once or press a button so the wireless unit is active.</li><li><strong>Enter pairing mode.</strong> Hold the junction-box or rear-derailleur button for about two seconds, until its indicator lights flash.</li><li><strong>Open Bike Connect.</strong> Grant Bluetooth access when prompted and choose Pair Bike.</li><li><strong>Select the bike.</strong> Keep the device nearby and choose the matching bike from the scan results.</li><li><strong>Confirm live data.</strong> Battery, firmware, or gear information should appear after connection.</li></ol></section>
        <section id="actions"><h2>Choose actions for each button</h2><p>Bike Connect can assign separate single- and double-tap actions to the left and right programmable buttons. Available actions depend on the platform.</p><ul><li>Play, pause, next, previous, mute, and volume control for compatible media apps</li><li>Podcast-style skip forward or back where supported</li><li>Toggle or briefly flash the phone light</li><li>Ring a built-in or custom virtual bell</li><li>Trigger keyboard shortcuts on Mac for indoor-cycling and other apps</li></ul><p>Test every mapping while stationary before relying on it during a ride.</p></section>
        <section id="platforms"><h2>Platform notes</h2><h3>iPhone and Android</h3><p>Keep the device mounted or locked. Once Bluetooth access and background behavior are enabled, mapped controls can continue without Bike Connect remaining in the foreground.</p><h3>Apple Watch</h3><p>The watch app can connect directly to a compatible bike for gear information and bell actions without an iPhone connection.</p><h3>Mac</h3><p>Assign standard or custom keyboard shortcuts to control an indoor-cycling app, music, volume, or another Mac workflow from the handlebars.</p></section>
        <section id="troubleshooting"><h2>If pairing or controls do not work</h2><ul><li>Disconnect E-TUBE PROJECT Cyclist and any other app using the bike connection.</li><li>Wake the bike and repeat pairing mode close to your device.</li><li>Confirm Bluetooth permission remains enabled for Bike Connect.</li><li>Restore hood buttons to their default D-FLY configuration if the wrong action fires.</li><li>Check the bike battery and firmware, then restart Bike Connect.</li></ul><p>See <a href="/support">Bike Connect Support</a> for detailed bell, background-control, and reconnect guidance.</p></section>
      </article><aside className="content-sidebar" aria-label="On this page"><nav className="contents-card"><strong>On this page</strong><a href="#requirements">Requirements</a><a href="#pair">Pair your bike</a><a href="#actions">Map actions</a><a href="#platforms">Platform notes</a><a href="#troubleshooting">Troubleshooting</a></nav></aside></div>
      <section className="content-cta"><div className="container-narrow"><h2>Make every button count.</h2><p>Get Bike Connect and build the handlebar controls that fit your ride.</p><StoreButtons placement="content" /></div></section>
    </main><Footer /></>
  )
}

export default Guide
