import './ContentPage.css'
import { Footer, Header, StoreButtons } from './SiteChrome'

function Support() {
  return (
    <><Header /><main id="main-content" className="content-page">
      <header className="content-hero"><div className="container content-hero-inner"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span>Support</span></nav><p className="eyebrow">Bike Connect Support</p><h1>Get your controls back on the bars.</h1><p className="content-hero-intro">Pairing instructions and practical fixes for compatibility, background controls, bells, button mapping, and bike connections.</p></div></header>
      <div className="container content-layout"><article className="content-main">
        <div className="answer-box"><strong>New to Bike Connect?</strong><p>Start with the <a href="/how-to-control-your-phone-with-shimano-di2-buttons">complete Di2 button setup guide</a>. It covers requirements, pairing, action mapping, and your first test ride.</p></div>
        <section id="quick-start"><h2>Quick start checklist</h2><ol className="numbered-steps"><li><strong>Wake the bike.</strong> Shift once or press a button so the Bluetooth module is active.</li><li><strong>Enter pairing mode.</strong> Hold the button on the junction box or rear derailleur for about two seconds, until its status lights flash.</li><li><strong>Pair in Bike Connect.</strong> Grant Bluetooth permission, choose Pair Bike, and select your bike.</li><li><strong>Map your buttons.</strong> Assign single and double taps for the left and right hood controls.</li><li><strong>Test before riding.</strong> Confirm each action while stationary, then leave the app open or lock your screen.</li></ol></section>
        <section id="compatibility"><h2>Compatibility</h2><div className="requirements-grid"><div className="requirement-card"><strong>Modern road Di2</strong><p>DURA-ACE R9200, ULTEGRA R8100, and SHIMANO 105 R7100</p></div><div className="requirement-card"><strong>GRX Di2</strong><p>RX825 and RX827; RX815 and RX817 with compatible D-FLY wireless hardware</p></div><div className="requirement-card"><strong>11-speed road Di2</strong><p>DURA-ACE R9150/R9170 and ULTEGRA R8050/R8070 with EW-WU101 or EW-WU111</p></div><div className="requirement-card"><strong>MTB Di2</strong><p>XTR M9250/M9050, DEORE XT M8250/M8050, and DEORE M6250; older systems need compatible Bluetooth hardware such as SC-MT800</p></div><div className="requirement-card"><strong>Required controls</strong><p>Readable hood, top, or shift-switch buttons exposed over Bluetooth LE</p></div><div className="requirement-card"><strong>Devices</strong><p>iPhone, iPad, Android, Mac, or Apple Watch with Bluetooth</p></div></div><p>Bluetooth LE is required, but the exact component and firmware combination must also expose controls Bike Connect can read. Only one app can maintain the bike connection at a time, so disconnect E-TUBE PROJECT Cyclist and other bike apps before opening Bike Connect.</p></section>
        <section id="pairing"><h2>Pairing and reconnecting</h2><h3>The bike does not appear</h3><ul><li>Confirm the bike battery is charged and its firmware is current.</li><li>Wake the Bluetooth module with a shift or hood-button press.</li><li>Enter pairing mode again and keep the device close to the bike.</li><li>Close any other app that may already be connected.</li><li>Toggle Bluetooth off and on, then reopen Bike Connect.</li></ul><h3>Reconnect without pairing again</h3><p>If the bike was previously paired, press a shift or hood button to wake it. Bike Connect should reconnect when its Bluetooth module becomes available.</p></section>
        <section id="background"><h2>Background controls and bell audio</h2><h3>Can the app run while the screen is locked?</h3><p>Yes. Once paired and granted Bluetooth access, mapped controls can continue while Bike Connect is in the background or the screen is locked.</p><h3>The bell notification is silent</h3><ul><li>Confirm the device ringer and media volume are audible.</li><li>Check the selected bell and preview it from Bike Connect settings.</li><li>If a paired Apple Watch receives the notification instead, review notification delivery or temporarily disconnect the watch while testing.</li><li>On supported Apple devices, enable notification-based bell playback for locked-screen use.</li></ul></section>
        <section id="buttons"><h2>Buttons trigger the wrong action</h2><p>Bike Connect expects the hood buttons to use their default D-FLY channel mapping. If a press is reported as the wrong side or control, restore the button configuration in Shimano’s E-TUBE PROJECT Cyclist app, disconnect that app, and reconnect with Bike Connect.</p><p>Bike Connect cannot modify shifting or bike configuration. It only reads button presses and bike status.</p></section>
        <section id="contact" className="contact-card"><h2>Still need help?</h2><p>Search or ask in GitHub Discussions first. For bugs, include your bike/groupset, wireless unit if applicable, device model, operating-system version, Bike Connect version, and exact reproduction steps.</p><div className="support-actions"><a className="action-button action-button-primary" href="https://github.com/superturboryan/Bike-Connect/discussions" target="_blank" rel="noopener noreferrer">Open Discussions</a><a className="action-button" href="https://github.com/superturboryan/Bike-Connect/issues/new" target="_blank" rel="noopener noreferrer">Report a bug</a><a className="action-button" href="mailto:watchcloud.app@gmail.com?subject=Bike%20Connect%20Support">Email support</a></div></section>
      </article><aside className="content-sidebar" aria-label="On this page"><nav className="contents-card"><strong>On this page</strong><a href="#quick-start">Quick start</a><a href="#compatibility">Compatibility</a><a href="#pairing">Pairing</a><a href="#background">Background and bell</a><a href="#buttons">Button mapping</a><a href="#contact">Get help</a></nav></aside></div>
      <section className="content-cta"><div className="container-narrow"><h2>Ready for another ride?</h2><p>Choose your platform and put the controls back under your thumbs.</p><StoreButtons placement="content" /></div></section>
    </main><Footer /></>
  )
}

export default Support
